
import { Session, Category, SessionType } from './types';

export const AGENDA: Session[] = [
  // DAY 1
  {
    id: 'd1-1',
    day: 1,
    startTime: '09:30',
    endTime: '09:45',
    title: "Chairperson’s Welcome (Opening)",
    speakers: ['Christina Lovelock (Author, BCS)'],
    relevance: 3,
    categories: [Category.GENERAL],
    type: SessionType.TALK,
    venue: 'Gold Track Room'
  },
  {
    id: 'd1-2',
    day: 1,
    startTime: '09:45',
    endTime: '10:25',
    title: 'Panel: Unifying teams for successful digital transformation',
    speakers: ['Steve Westgarth', 'Ingrid Olmesdahl', 'Laura Fiacco', 'German Faraoni', 'Haider Alleg', 'Caroline Mørck Jensen'],
    relevance: 4,
    categories: [Category.CHANGE_MGMT, Category.HUMAN_CENTRIC],
    type: SessionType.PANEL,
    venue: 'Gold Track Room'
  },
  {
    id: 'd1-3',
    day: 1,
    startTime: '10:30',
    endTime: '10:50',
    title: 'The Path to Agentic AI Transformation',
    speakers: ['Brian Halpin (SS&C Blue Prism)'],
    relevance: 5,
    categories: [Category.AGENTIC_AI, Category.AI_STRATEGY],
    type: SessionType.TALK,
    venue: 'Gold Track Room'
  },
  {
    id: 'd1-4',
    day: 1,
    startTime: '10:55',
    endTime: '11:25',
    title: 'Designing the AI-Ready Network: Sovereign, Secure & Always On',
    speakers: ['Julian Skeels (Expereo)'],
    relevance: 4,
    categories: [Category.INFRASTRUCTURE, Category.AI_STRATEGY],
    type: SessionType.TALK,
    venue: 'Gold Track Room'
  },
  {
    id: 'd1-5',
    day: 1,
    startTime: '11:25',
    endTime: '12:05',
    title: 'Networking Break',
    speakers: [],
    relevance: 2,
    categories: [Category.NETWORKING],
    type: SessionType.BREAK,
    venue: 'Networking Lounge'
  },
  {
    id: 'd1-6',
    day: 1,
    startTime: '12:05',
    endTime: '12:35',
    title: 'AI-Powered Transformation: What questions should we ask?',
    speakers: ['Ravi Jay (Sanofi)'],
    relevance: 5,
    categories: [Category.AI_STRATEGY, Category.DATA_ANALYTICS],
    type: SessionType.TALK,
    venue: 'Gold Track Room'
  },
  {
    id: 'd1-7',
    day: 1,
    startTime: '12:40',
    endTime: '13:00',
    title: 'Who Says You Need to Lose Control to Transform',
    speakers: ['Aaron Martin (NextCloud)'],
    relevance: 4,
    categories: [Category.INFRASTRUCTURE, Category.DATA_ANALYTICS],
    type: SessionType.TALK,
    venue: 'Gold Track Room'
  },
  {
    id: 'd1-8',
    day: 1,
    startTime: '13:05',
    endTime: '13:15',
    title: 'AI & Data-Led Digital Transformation with BlueGecko',
    speakers: ['Emilio Piers (Nextgenlytics)', 'Ankur Anand (Nash Squared)'],
    relevance: 4,
    categories: [Category.DATA_ANALYTICS, Category.AI_STRATEGY],
    type: SessionType.TALK,
    venue: 'Gold Track Room'
  },
  {
    id: 'd1-9',
    day: 1,
    startTime: '13:15',
    endTime: '14:15',
    title: 'Lunch Break',
    speakers: [],
    relevance: 1,
    categories: [Category.NETWORKING],
    type: SessionType.BREAK,
    venue: 'Dining Hall'
  },
  {
    id: 'd1-10',
    day: 1,
    startTime: '14:15',
    endTime: '14:55',
    title: 'Panel: Digital transformation successes & failures',
    speakers: ['Rob Clifford MBE', 'Guy Dulake', 'Regina Quartey', 'Paul Blackwell', 'Edward Pikett'],
    relevance: 3,
    categories: [Category.HUMAN_CENTRIC, Category.CHANGE_MGMT],
    type: SessionType.PANEL,
    venue: 'Gold Track Room'
  },
  {
    id: 'd1-11',
    day: 1,
    startTime: '15:00',
    endTime: '15:20',
    title: 'How Microsoft & Prosci Are Redefining Change Success in the AI Era',
    speakers: ['Emma de-la-Haye', 'Steve Green'],
    relevance: 4,
    categories: [Category.CHANGE_MGMT, Category.AI_STRATEGY],
    type: SessionType.TALK,
    venue: 'Gold Track Room'
  },
  {
    id: 'd1-12',
    day: 1,
    startTime: '15:20',
    endTime: '15:40',
    title: 'From Roadmap to Reality: Executing Digital Transformation That Actually Lands',
    speakers: ['Mathew Thomas (Reckitt)'],
    relevance: 4,
    categories: [Category.CHANGE_MGMT, Category.HUMAN_CENTRIC],
    type: SessionType.TALK,
    venue: 'Gold Track Room'
  },
  {
    id: 'd1-13',
    day: 1,
    startTime: '15:40',
    endTime: '17:30',
    title: 'Expo & Co-Located Events / AI & Big Data Expo Sessions',
    speakers: ['Various'],
    relevance: 4,
    categories: [Category.DATA_ANALYTICS, Category.AGENTIC_AI],
    type: SessionType.EXPO,
    venue: 'Expo Floor',
    isCoLocated: true
  },

  // DAY 2
  {
    id: 'd2-1',
    day: 2,
    startTime: '09:30',
    endTime: '09:45',
    title: 'Chairperson’s Welcome',
    speakers: ['Kathryn Lancioni'],
    relevance: 3,
    categories: [Category.GENERAL],
    type: SessionType.TALK,
    venue: 'Gold Track Room'
  },
  {
    id: 'd2-2',
    day: 2,
    startTime: '09:45',
    endTime: '10:25',
    title: 'Panel: How to innovate, motivate & cultivate teams with systematic company-wide shifts',
    speakers: ['Paul Beswick', 'Michal Kendereski', 'Jon David Carman', 'Haider Alleg'],
    relevance: 4,
    categories: [Category.HUMAN_CENTRIC, Category.CHANGE_MGMT],
    type: SessionType.PANEL,
    venue: 'Gold Track Room'
  },
  {
    id: 'd2-3',
    day: 2,
    startTime: '10:30',
    endTime: '11:00',
    title: 'Don’t Let AI Be Your “B-Movie Robot”: Why Analytics Must Come Before the Hype',
    speakers: ['DP Indetkar (Northern Trust)'],
    relevance: 5,
    categories: [Category.DATA_ANALYTICS, Category.AI_STRATEGY],
    type: SessionType.TALK,
    venue: 'Gold Track Room'
  },
  {
    id: 'd2-4',
    day: 2,
    startTime: '11:05',
    endTime: '11:15',
    title: 'The Role of Connectivity in Digital Transformation',
    speakers: ['Tim Patrick (Blue Wireless)'],
    relevance: 3,
    categories: [Category.INFRASTRUCTURE],
    type: SessionType.TALK,
    venue: 'Gold Track Room'
  },
  {
    id: 'd2-5',
    day: 2,
    startTime: '11:15',
    endTime: '12:05',
    title: 'Networking Break',
    speakers: [],
    relevance: 2,
    categories: [Category.NETWORKING],
    type: SessionType.BREAK,
    venue: 'Networking Lounge'
  },
  {
    id: 'd2-6',
    day: 2,
    startTime: '12:05',
    endTime: '12:15',
    title: 'Transform enterprise workflows: Extending processes to Microsoft Teams',
    speakers: ['Mohammed Jaffer Ali (Arch)'],
    relevance: 3,
    categories: [Category.AI_STRATEGY, Category.HUMAN_CENTRIC],
    type: SessionType.TALK,
    venue: 'Gold Track Room'
  },
  {
    id: 'd2-7',
    day: 2,
    startTime: '12:15',
    endTime: '12:30',
    title: 'Overcoming data governance & transformation complexity in contract lifecycle',
    speakers: ['Luke Sinclair (Adecco)'],
    relevance: 3,
    categories: [Category.DATA_ANALYTICS],
    type: SessionType.TALK,
    venue: 'Gold Track Room'
  },
  {
    id: 'd2-8',
    day: 2,
    startTime: '12:30',
    endTime: '13:00',
    title: 'Beyond Giants and Startups: Practical Transformation for Real-World Businesses',
    speakers: ['TBD'],
    relevance: 3,
    categories: [Category.HUMAN_CENTRIC, Category.AI_STRATEGY],
    type: SessionType.TALK,
    venue: 'Gold Track Room'
  },
  {
    id: 'd2-9',
    day: 2,
    startTime: '13:00',
    endTime: '15:30',
    title: 'Co-Located Expo & AI & Big Data Expo Deep Dives',
    speakers: ['Various'],
    relevance: 4,
    categories: [Category.DATA_ANALYTICS, Category.AGENTIC_AI, Category.AI_STRATEGY],
    type: SessionType.EXPO,
    venue: 'Expo Floor',
    isCoLocated: true
  }
];
